name: Build and Release

on:
  push:
    tags:
      - '**'  # Matches any tag

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Copy LICENSE.md to dist folder
        run: cp LICENSE.md dist/
        shell: bash

      - name: Create ZIP Archive
        run: |
          cd dist
          zip -r ../chosen-assets-v${{ github.ref_name }}.zip ./*
        shell: bash

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./chosen-assets-v${{ github.ref_name }}.zip
          asset_name: chosen-assets-v${{ github.ref_name }}.zip
          asset_content_type: application/zip
